// <auto-generated />
using E_commerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240408095728_ProductSeeding2")]
    partial class ProductSeeding2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E_commerce.shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A handheld personal computer (PC), typically built around either a clamshell form factor or a gaming form factor with a gamepad integrated for video games, is a mobile device that is significantly smaller than any standard personal computer (PC), but based on the same principles as PCs. The clamshell form factor is sometimes referred to as a palmtop computer, not to be confused with Palmtop PC which was a name used mainly by Hewlett-Packard.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.qXcocaHp2V8brplkQX9a0gHaE7?rs=1&pid=ImgDetMain",
                            Price = 77.5m,
                            Title = "Handheld PC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Hitchhiker's Guide to the Galaxy[a][b] is a comedy science fiction franchise created by Douglas Adams. Originally a 1978 radio comedy broadcast on BBC Radio 4, it was later adapted to other formats, including novels, stage shows, comic books, a 1981 TV series, a 1984 text adventure game, and 2005 feature film.",
                            ImageUrl = "https://www.themoviedb.org/t/p/original/hmGMMcehDlTdiBEnq3fAc5QOkS1.jpg",
                            Price = 75.4m,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ready Player One is a 2018 American science fiction action film based on Ernest Cline's novel of the same name. The film was co-produced and directed by Steven Spielberg, written by Cline and Zak Penn, and stars Tye Sheridan, Olivia Cooke, Ben Mendelsohn, Lena Waithe, T.J. Miller, Simon Pegg, and Mark Rylance.",
                            ImageUrl = "https://theculturednerd.org/wp-content/uploads/2020/04/1_Nzaxn52WDFE7BTois8ZQ7w-1382x2048.jpeg",
                            Price = 88.5m,
                            Title = "Ready Player One (film)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
